version: '3.8'
services:
  test_udv:
    build: .
    container_name: test_udv
    volumes:
      - ./output:/app/output
    environment:
      SSH_HOST: 192.168.1.101
      SSH_PORT: 22
      SSH_USERNAME: test
      SSH_PASSWORD: test123
    command: python main.py